import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#040316',
        paddingHorizontal: 25,
      },
      content: {
        alignItems: 'center',
        alignSelf: 'center',
        justifyContent: 'center',
        flex: 1,
        width: '100%',
        height: 200,
        marginBottom: 20,
        backgroundColor: '#f1f1f1',
        borderRadius: 10,
        overflow: 'hidden',
      },
      containerEventos: {
        position: 'relative',
        width: '100%',
        height: '75%',
        textAlign: 'center',
        bottom: 35,
      },
      images: {
        width: '100%',
        height: '100%',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
      },
      textContainer: {
        position: 'absolute',
        top: 130,
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        backgroundColor: '#3E4A59',
        paddingTop: 10,
        paddingLeft: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
      },
      textOne: {
        color: '#fff',
        textAlign: 'left',
        fontSize: 18,
        fontWeight: 'bold',
      },
      textTwo: {
        color: '#fff',
        textAlign: 'left',
        fontSize: 16,
        fontWeight: 'bold',
      },
      textThree: {
        color: '#fff',
        textAlign: 'left',
        fontSize: 16,
        fontWeight: 'bold',
      },
      category: {
        marginTop: 5,
        marginBottom: -7,
        width: '85%',
        height: 'auto',
        alignSelf: 'center',
      },
      textCategory: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 21,
        padding: 10,
      },
});